POST  http://localhost:8080/events
Content-Type: application/json

{
    "name" : "test event",
    "description" : "A test event",
    "location" : "test location",
    "dateTime" : "2025-01-15T15:30:00.000Z"
}
