POST  http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImV4YW1wbGVAY29tIiwiZXhwIjoxNzEzMjAwNDk1LCJ1c2VySWQiOjF9.B2TPhbMffDg4h0ZbN1nvy9_7TqkzAQpSx1UmQvO_XCA

{
    "name" : "test event 3",
    "description" : "A test event 3",
    "location" : "test location",
    "dateTime" : "2025-01-15T15:30:00.000Z"
}
